omf2097/openomf

- .travis.yml
- CMakeLists.txt
Lots of distro's are still shipping CMake 2.8, so it would be rather nice to keep CMake 2.8 compatibility for another year or so.
Also, a minor tweak to the window title.
> Lower CMake version

- CMakeLists.txt
- INSTALL.md
- src/resources/pathmanager.c
The default resource path on linux, in release mode, is now
../share/games/openomf/, relative to the binary. This can be overridden
by the environment variable OPENOMF_RESOURCE_DIR, which should be an
absolute path with a trailing slash.
A similar environment variable override is provided for the plugin path:
OPENOMF_PLUGIN_DIR.
cc @katajakasa @animehunter
> Change unix default resource path, add environment variable overides

- src/game/scenes/vs.c
ref to #292 
Sorry, did a little mess with github...
Now with corrections suggested, and a new branch from my fork :)
On a side note, should PILOT_KREISSACK be applied also on line 270 for better readability?
else if (player2->pilot_id == 10 && settings_get()->gameplay.difficulty < 2)
> Force Arena 0 when fighting Kreissack in 1 player mode - with corrections

- src/game/objects/har.c
Partially related to #290
In OMF 2.1, if a HAR has little health, a shot which bring its health to 0 will end the match.
In OpenOMF, in same situation, the HAR is still standing because there is some endurance left.
This PR should make things much in line with OMF behaviour
(I hope a pair of reset and force push on my fork were succesful to produce a clean PR :) )
> HARs have to go down if a hit bring them at 0 health, no matter endurance

- .travis.yml
Travis-CI has new, docker based build boxes available that they claim are harder, better, faster and stronger. We should switch. 
For easier libsdl2-dev installation we need this: https://github.com/travis-ci/apt-source-whitelist/issues/45
> Docker based Travis-CI builds

- src/game/objects/har.c
As per PR #298 , these lines are useless.
This PR also avoids rare occasions in which HAR could stand up at 0 health.
> remove some endurance useless checks

- include/utils/hashmap.h
- src/utils/hashmap.c
- testing/test_hashmap.c
1. Creates a new hashmap bucket list
2. Rehashes nodes from the old list and adds them to the new list
3. frees up old list and sets the new list as hashmap main bucket list.
Also adds the autoresize stuff.
This can and should be optimized!
> Add a naive implementation of hashmap resizing function

- src/formats/script.c
sizeof(tmp)-s can easily be less than zero there, and since tmp is not
used elsewhere, we can just remove the -s.
> formats: Fix buffer overflow in sd_script_encoded_length()

- src/formats/internal/reader.c
This fixes valgrind error Conditional jump or move depends on
uninitialised value(s).
> formats: Check sd_peek_buf() return value before comparing buffers

- src/formats/script.c
This addresses a static analyzer complaint.
> formats: Break loop instead of modifying the loop counter in body

- src/controller/net_controller.c
This was giving rtt horrible values.
> controller: Stop dividing by zero in avg_rtt()

- src/audio/sources/dumb_source.c
- src/main.c
Move all libdumb usage to dumb_source.c. This is safe, as dumb_register_stdfiles() can be called repeatedly, and dumb_exit() will only clear cache (it will be re-filled when needed).
This removes libdumb stuff from main.c. We will probably drop this later, as libxmp seems to be available everywhere and has equal playback quality.
> Move all libdumb calls to dumb_source.c

- src/game/scenes/arena.c
This makes the player to lose a rank position in the tournament when a match is lost.
A check is added to avoid going out of the array list of ranked participants if the player loses the match while being already at the bottom of the ladder.
> Rank loss in tournament

- CMakeLists.txt
I have faced this error during the PS2 port.
The current `cmake` was always overriding the flags we were passing, it should instead just append the needed ones.
Cheers.
> Don't wipe existing flags

- src/game/gui/menu.c
This prevents a deadlock when keybinding when the user tries to bind to up/down and that key is already bound.
> Check if component supports select first

- .github/workflows/compilation.yml
Goal is to implement #509 - omf assets bundling on release packages
> Asset bundling

- src/formats/script.c
- src/formats/script.h
> Fix remaining memory leaks

- src/game/gui/dialog.c
- src/game/gui/textbutton.c
- src/game/gui/textinput.c
- src/game/gui/textselector.c
- src/game/gui/textslider.c
- src/game/scenes/arena.c
- src/game/scenes/mainmenu/menu_audio.c
- src/game/scenes/mainmenu/menu_configuration.c
- src/game/scenes/mainmenu/menu_connect.c
- src/game/scenes/mainmenu/menu_gameplay.c
- src/game/scenes/mainmenu/menu_input.c
- src/game/scenes/mainmenu/menu_keyboard.c
- src/game/scenes/mainmenu/menu_listen.c
- src/game/scenes/mainmenu/menu_main.c
- src/game/scenes/mainmenu/menu_net.c
- src/game/scenes/mainmenu/menu_presskey.c
- src/game/scenes/mainmenu/menu_video.c
- src/game/scenes/mainmenu/menu_video_confirm.c
- src/game/scenes/mechlab/lab_dash_newplayer.c
- src/game/scenes/mechlab/lab_menu_confirm.c
- src/game/scenes/mechlab/lab_menu_difficultyselect.c
- src/game/scenes/mechlab/lab_menu_select.c
- src/game/scenes/melee.c
- src/game/scenes/newsroom.c
- src/game/scenes/vs.c
- src/video/color.h
> game: Add initial financial report

- src/game/protos/fight_stats.h
- src/game/scenes/arena.c
- src/game/scenes/vs.c
> game: Add fight statistics view

- src/resources/trnmanager.c
This reverts commit 0ba01ed2cb1e01d50bee992d65d936d446d5db42.
> Revert "resources: Free sd_tournament_file nodes in trnmanager list"

- src/formats/chr.c
- src/formats/pilot.c
- src/formats/pilot.h
- src/resources/trnmanager.c
This reverts commit 9465d97a9f01f1fd706b03e094c8f67e972723ff.
> resources: Free sd_tournament_file nodes in trnmanager list

- src/game/objects/har.c
- src/game/objects/har.h
- src/game/objects/projectile.c
- src/game/objects/projectile.h
- src/game/protos/object.c
- src/game/protos/object.h
- src/game/protos/scene.c
- src/resources/af.c
- src/resources/af.h
- src/resources/af_move.c
- src/resources/af_move.h
- src/resources/animation.c
- src/resources/animation.h
- src/resources/bk.c
- src/resources/bk.h
- src/resources/bk_info.c
- src/resources/bk_info.h
- src/resources/sprite.c
- src/resources/sprite.h
- src/utils/array.c
- src/utils/array.h
This attempts to preserve the deduping of sprites in the AF files when loading them into the game.
This branch appears to save about 1.2mb of sprites.
However, this branch seems to also cause some weird leaks, and some crashes when HARs jump, so it needs more work.
> Reduce RAM by deduping sprites

- BUILD.md
Hi, tried to build the project for the first time using the instructions in BUILD.md and noticed they were missing one recently added dependency.
Also upgraded the assets pack URL to HTTPS to avoid an unnecessary redirect from the insecure URL.
> BUILD.md: include libepoxy in apt-get & homebrew package lists

- src/game/gui/textbutton.c
Render after the border box, which is no longer transparent for some reason.
> Fix the dialog box button text render order

- .gitignore
.cache and compile_commands.json are for use with clangd
https://clangd.llvm.org/design/compile-commands
https://stackoverflow.com/questions/51402740/visual-studio-code-clangd-extension-configuration#51692215
the build instructions BUILD.md states:
> On Linux in debug mode, the OMF resource files should be put in resources/ subdirectory.
To prevent these from being checked in accidentally (and generally ruining my git status), each file from omf2097-assets.zip is now gitignored.
> Gitignore clangd files

- src/utils/str.c
- testing/test_str.c
- Strings of length 15 were being missed by the small string optimization,
- str_replace would always resize the string before replacing (potentially truncating the contents), and
- str_replace no longer falls into an infinite loop when replacement contains seek, and can find consecutive hits even with an empty replacement.
~~Also .gitignore'd the test artifacts, clangd compile_commands.json & .cache, and any untracked files added to /resources (typically the OMF 2097 assets).~~
> `str` String fixes

- .github/workflows/compilation.yml
- CMakeLists.txt
- cmake-scripts/FindSDL2.cmake
- cmake-scripts/FindSDL2_mixer.cmake
- cmake-scripts/Findargtable2.cmake
- cmake-scripts/Findargtable3.cmake
- cmake-scripts/Findconfuse.cmake
- cmake-scripts/Findxmp.cmake
- src/console/console.c
- src/console/console_cmd.c
- src/formats/bk.c
- src/formats/internal/reader.c
- src/formats/language.c
- src/formats/pic.c
- src/formats/setup.h
- src/formats/tournament.c
- src/formats/vga_image.c
- src/game/objects/har.c
- src/game/protos/intersect.c
- src/main.c
- src/resources/pathmanager.c
- src/resources/sgmanager.c
- src/utils/scandir.c
- src/video/opengl/object_array.c
- src/video/opengl/shaders.c
- src/video/opengl/shared.c
- src/video/opengl/texture_atlas.c
- vcpkg.json
Fixes compilation with MSVC.
With `/Wall`, MSVC currently generates ~13,000 warnings when compiling openomf & core; mostly repeated warnings about padding in SDL headers.
VCPKG is introduced & used to install dependencies.
A Github Action check_msvc is added to ensure MSVC does not regress, but it does not emit a release artifact (as we already ship a mingw release, and I'd rather not port the zip packaging steps to powershell at this moment).
> Fix MSVC Compilation

- CMakeLists.txt
- src/game/scenes/lobby.c
- src/game/scenes/mainmenu/menu_listen.c
- src/game/utils/nat.c
- src/game/utils/nat.h
- src/game/utils/settings.c
- src/game/utils/settings.h
- src/main.c
Makes the following fields configurable from settings:
* Internal port range to bind to
* External port range to map to, using upnp or PMP
* Whether to use upnp or PMP, or neither
* Username for lobby
Port 0 will mean "random port", ranges are inclusive, so 2097-2097 contains a single port, port 0 as an external port will first try to use the internal port, then fall back to using random.
> Make many network settings configurable:

- CMakeLists.txt
- cmake-scripts/Findminiupnpc.cmake
- cmake-scripts/Findnatpmp.cmake
- vcpkg-ports/libnatpmp/install-targets.patch
- vcpkg-ports/libnatpmp/libnatpmp-config.cmake.in
- vcpkg-ports/libnatpmp/portfile.cmake
- vcpkg-ports/libnatpmp/vcpkg.json
The link issue was because the MINIUPNP_STATICLIB and NATPMP_STATICLIB defines weren't being propogated from the dependency into openomf_core, which caused the headers to misbehave (and think they were part of a DLL build)
By linking to an imported cmake target we can be certain that any PUBLIC target_add_definitions in the libraries get to the openomf target we are linking them to, here openomf_core.
Unfortunately, [ubuntu's libminiupnpc-dev](https://packages.ubuntu.com/focal/amd64/libminiupnpc-dev/filelist) does not ship an exported cmake target (they are probably using the Makefile to build their package); if they did ship an exported cmake target, we would be able to rid ourselves of the Findminiupnpc.cmake script entirely and rely on find_package(CONFIG).
> Fix libnatpmp vcpkg port

- src/game/scenes/vs.c
23 columns of text need to be displayed for the arena description to wrap properly.
Also moved the arena name up a pixel to better match DOS & give more space for the description.
> Tweak vs arena select text_render size to fit Fire Pit description

- .github/workflows/compilation.yml
- CMakeLists.txt
- cmake-scripts/BuildLanguages.cmake
- resources/DANISH.TXT
- resources/DANISH2.TXT
- resources/ENGLISH2.TXT
- resources/GERMAN2.TXT
- src/formats/language.c
- src/formats/language.h
- src/game/gui/text_render.c
- src/game/gui/textselector.c
- src/game/scenes/mainmenu/menu_configuration.c
- src/game/scenes/mainmenu/menu_language.c
- src/game/scenes/mainmenu/menu_language.h
- src/game/scenes/newsroom.c
- src/game/utils/settings.c
- src/game/utils/settings.h
- src/resources/ids.c
- src/resources/ids.h
- src/resources/languages.c
- src/resources/languages.h
- src/utils/compat.h
- src/utils/cp437.c
- src/utils/cp437.h
- src/utils/scandir.c
- testing/test_cp437.c
- testing/test_main.c
- tools/languagetool/main.c
- tools/pcxtool/main.c
- vcpkg.json
New Configuration option "LANGUAGE" lets player choose their language.
- OMF ENGLISH.DAT and GERMAN.DAT are supported.
- Additional languages will be picked up, so long as they have a .LNG file extension; an example Danish Machine translation is added to demonstrate how to do this.
- text_render now renders characters 0x80..=0xFF, such as Ä, ß, and ü.
- OpenOMF-specific language strings are supported via a second language file, such as ENGLISH.DAT2 or DANISH.LNG2
- languagetool has been expanded to support encoding files (#693 has been rolled up into this PR)
- When building openomf, languagetool will be used to build the .DAT2 and DANISH language files. (See BuildLanguages.cmake)
- Languages are built and shipped in CI artifacts.
- Languagetool converts between UTF-8 and DOS CP 437. …
> Support Multiple Languages

- src/game/gui/dialog.c
- src/game/gui/label.c
- src/game/gui/text_render.c
- src/game/gui/textinput.c
- src/game/scenes/vs.c
label_create_with_width was abusing `text_find_max_strlen` thinking it produces the length of the longest line in the text after wrapping, when it in fact only produces the next line's length.
Kreissack's difficulty dialog is now wider than other dialogs, which is good
compare OMF 2097:
and OpenOMF (with these changes)
> Fixes for text dialog, kreissack dialog

- src/game/gui/text_render.c
- src/game/gui/text_render.h
- src/game/gui/textselector.c
- src/game/gui/textslider.c
Split text renderer a bit. Now we fetch the surface only once, and there is additional renderer function for rendering the text type (which already knows its own length).
> Split text renderer into more pieces

- src/game/scenes/mainmenu/menu_language.c
- src/utils/allocator.c
- src/utils/allocator.h
- src/utils/allocator_default.h
- Move allocators to a header and mark them "static inline". This should make the compiler inline the functions wherever needed.
- Add a way to make the allocator functions different per platform.
> Platform specific allocators

- src/utils/allocator_default.h
```
/home/andrew/openomf/src/utils/allocator_default.h:14:17: error: call to undeclared library function 'malloc' with type 'void *(unsigned long)'; ISO C99 and later do not support implicit function declarations [clang-diagnostic-implicit-function-declaration]
14 |     void *ret = malloc(size);
|                 ^
/home/andrew/openomf/src/utils/allocator_default.h:14:17: note: include the header <stdlib.h> or explicitly provide a declaration for 'malloc'
```
> Fix mising include in allocator_default.h

- src/game/protos/player.c
Fixes unwanted fades during animations that shake the screen (bb, bl), and animations that play other animations (bm, bj)
Note that bm and bj have handling lower down in player.c (away from the blend modes), that'll hopefully get fixed sometime.
the bug in question:
> bb, bl, bm, and bj should not set blend_finish

- src/game/gui/dialog.c
- src/game/protos/object.c
When adding (or otherwise changing) `vga_state_enable_palette_transform` calls, please ensure there are corresponding `vga_state_disable_palette_transform` calls to prevent use-after-frees.
Also a really minor cleanup in dialog.c
> Fix palette crash again

- src/engine.c
- src/game/game_state.c
- src/game/game_state.h
- src/game/objects/har.c
- src/game/protos/object.c
- src/game/protos/object.h
- src/video/damage_tracker.c
- src/video/damage_tracker.h
- src/video/vga_state.c
- src/video/vga_state.h
Objects now have a `palette_transform` field to store their palette transformer callback.
`vga_render` now calls into game_state and object to gather all the palette transformers for the render.
Much like PR 756, `vga_state_render` will now calculate the palette data on the first frame all transformers are off, to ensure the current palette is updated to match the base palette. This solves the bug where palette transformer's effects persist after removal.
Obsoletes PR #756
EDIT: removed vga_state_tick layer of laziness/change detection-- transformers are now gathered every render frame
> Treat object palette transformers like other cb's

- src/game/game_state.c
- src/game/game_state_type.h
- src/game/objects/har.c
- src/game/scenes/arena.c
- src/game/scenes/melee.c
- src/game/scenes/newsroom.c
- src/game/utils/har_screencap.c
- src/game/utils/har_screencap.h
- src/video/surface.c
- src/video/surface.h
- src/video/video.c
- src/video/video.h
New:
1. Newsroom shows robots in color
2. Newsroom "final blow" capture will zoom out to show both robots as needed
3. Arena overlay UI is now hidden in captures (the round token objects are unfortunately still present)
1 and 2 are for parity with the original game, 3 is extra.
future work:
- the original game's seamless transition from arena to newsroom
- improve camera positioning + sizing logic
- hide objects in captures, chiefly the round token objects.
- shadow's shadows currently all show up in color, haven't checked what the original does
> Slightly better Newsroom Captures

- src/formats/palette.c
- src/game/scenes/cutscene.c
- src/game/scenes/newsroom.c
Fixes https://github.com/omf2097/openomf/issues/755
Show the "New champion" text on top of the photo.
> Show the 'new champion' text in newsroom

- CMakeLists.txt
A few things were being done wrong before, with no negative repercussions that I know of:
- using deprecated PNG_LIBRARY variable instead of PNG_LIBRARIES
- not consuming PNG_DEFINITIONS
- linking PNG to the exe targets (openomf, languagetool, etc..) instead of directly to openomf_core where it's used (this is a bit pedantic, but makes things easier).
- explicitly depending on ZLIB. This is unneeded when using FindPNG properly, and openomf does not directly use zlib.
this PR switches from the FindPNG variables to the PNG::PNG imported target that [FindPNG has been defining since cmake 3.5](https://cmake.org/cmake/help/latest/module/FindPNG.html)
PNG_LIBRARIES and such broke after vcpkg's PR https://github.com/microsoft/vcpkg/pull/42058, but I don't feel like debugging why PNG_FOUND was …
> Fix vcpkg-specific PNG link errors

- src/formats/internal/memreader.c
- src/formats/sprite.c
- src/resources/sprite.c
- src/utils/allocator.h
- src/utils/allocator_default.h
allocator.h now has doc strings for the various methods it provides.
Notably, omf_malloc(0) and similar calls now have well-specified behavior (rather than libc implementation-specified behavior): it aborts the program with an error message
>  Document allocator.h API, fail on omf_malloc(0)

- src/game/objects/har.c
- src/utils/c_string_util.c
- src/utils/c_string_util.h
- src/utils/str.c
- src/utils/str.h
- testing/misc/parser_test_strings.c
- testing/test_main.c
- testing/test_str.c
str.h strings now store more characters in a small string than before, store the heap capacity for large strings (to avoid useless reallocs), and all this without increasing the size of struct str or additional heap usage.
Heavily inspired by Facebook's fbstring as described in a 2016 CppCon talk: https://youtu.be/kPR8h4-qZdk (although that has additional bells and whistles, including CoW semantics for very large strings).
> Improve str strings

- CMakeLists.txt
Fixes regression from cmake dependencies refactor.
```
CMake Error at CMakeLists.txt:318 (include):
include could not find requested file:
ClangFormat
CMake Error at CMakeLists.txt:330 (clangformat_setup):
Unknown CMake command "clangformat_setup".
```
> CMake: Provide path to ClangFormat.cmake

- CMakeLists.txt
- src/controller/ai_controller.c
- src/game/objects/har.c
- src/game/objects/scrap.c
- src/game/protos/player.c
- src/game/scenes/arena.c
- src/game/scenes/scoreboard.c
- src/game/utils/nat.c
- src/game/utils/score.c
- src/main.c
- src/utils/compat.h
- src/utils/scandir.c
- src/video/renderers/opengl3/helpers/bindings.c
- src/video/renderers/opengl3/helpers/object_array.c
- testing/test_script.c
- tools/afdiff/main.c
- tools/aftool/main.c
- tools/altpaltool/main.c
- tools/bktool/main.c
- tools/chrtool/main.c
- tools/fonttool/main.c
- tools/languagetool/main.c
- tools/pcxtool/main.c
- tools/pictool/main.c
- tools/rectool/main.c
- tools/scoretool/main.c
- tools/setuptool/main.c
- tools/soundtool/main.c
- tools/stringparser/main.c
- tools/trntool/main.c
- DEBUGMODE is now defined on MSVC debug builds
- VS_DEBUGGER_ENVIRONMENT now tells game where to find the resources and shaders, needed because build\resources is not next to build\Debug\openomf.exe (another solution I used previously was to copy the resources into build\Debug, but that's messy)
- Warnings are now either: silenced, treated as errors, and or fixed.
Enabling and fixing C4668 may be a bit silly, but I was feeling guilty about my habit of writing `#if XYZ` instead of `#ifdef XYZ` (where XYZ is maybe-defined, like __APPLE\_\_)
The following two warnings are now be disabled, and are comparable to GCC's -Wconversion; -Wconversion is not enabled on master branch. Banning implicit lossy conversions is a good idea for another time, but fixing them will generate a **lot** of line …
> MSVC Warning cleanup, /WX (Werror), and misc. fixes

- src/console/console_cmd.c
- src/engine.c
- src/game/objects/har.c
- src/game/protos/object.c
- src/game/protos/player.c
- src/game/protos/scene.c
- src/game/scenes/scoreboard.c
- src/game/utils/har_screencap.c
- src/video/vga_state.c
Mostly from running demo with warp speed until it crashes, then fixing the crash and repeating.
Changes that are not related to crashes:
- "Drop ticks that are extremely late" ensures that the game doesn't try to catch up for more than 100ms worth of ticks-- this solves the issue where the game goes warpspeed after hitting a debugger breakpoint or other extreme stall.
- Make stamina regenerate about three thousand times faster than before, scaling it by the endurance_max. Neither the old code nor the new code is truly faithful to the original game, but this makes it regenerate at a somewhat similar rate to the original (whereas before, the effect was not noticable)
> Fix some bugs, mostly crashes

- src/console/console.c
- src/controller/ai_controller.c
- src/game/common_defines.h
- src/game/game_state.c
- src/game/game_state.h
- src/game/gui/menu.c
- src/game/gui/menu_background.c
- src/game/gui/menu_background.h
- src/game/scenes/arena.c
- src/game/scenes/mainmenu/menu_main.c
- src/game/scenes/melee.c
- src/game/scenes/newsroom.c
- src/game/scenes/vs.c
- src/game/utils/score.c
- src/game/utils/score.h
Newsroom and VS are now part of the demo sequence.
This makes it possible to see the character-vs-themselves insults in openomf =)
Scores are now handled more like the original, hiding the score points for nonhuman players (here, two ai)
VITALITY and PERFECT ROUND score bonuses are now awarded every round (instead of just the final round), and only when a human player defeats an AI.
not changed:
- DEMO still does not visit the MELEE scene as Player 1, unlike the original game.
- Pilots will still use the Nova in demo mode (this is done in game_state_init_demo)
- Kreissack still does not appear in demo mode (but easily could, if we wanted him to. same function.)
> Show Newsroom and VS in DEMO mode and Score fixes

- src/game/scenes/melee.c
Fixes a bug where player 2's portrait doesn't render.
Occured because i made a typo a pr or two ago, where the game renders p1's portrait a second time instead of rendering p2's.
> Fix P2 pilot portrait regression

- src/game/scenes/cutscene.c
This fixes a compiler warning.
> game: Use omf_strdup() over strncpy() in cutscene_create()

- src/formats/chr.c
PR targets PR #823's branch (adt/pilot-genders), not master.
Removes the extraneous uint16-to-uint16 cast.
Using a pull request here to run a clang/gcc build in CI, so I can see the warning (if it is still generated).
> PR-on-PR: Remove extraneous u16-to-u16 cast

- src/formats/chr.c
- src/formats/chr.h
- src/formats/pilot.h
- src/game/common_defines.h
- src/game/scenes/melee.c
- src/game/scenes/newsroom.c
- src/game/scenes/newsroom.h
- src/resources/pilots.c
- src/resources/pilots.h
- tools/chrtool/main.c
When loading the CHR file, load the gender from the PIC file using the 10th byte of the unknown enemy footer.
For the tournament player, consult the PLAYERS.PIC for the gender.
> Fix pilot gender in tournament mode

- src/console/console_cmd.c
- src/controller/ai_controller.c
- src/controller/controller.h
- src/controller/keyboard.c
- src/controller/net_controller.c
- src/engine.c
- src/game/game_state.c
- src/game/game_state.h
- src/game/objects/har.c
- src/game/objects/har.h
- src/game/objects/hazard.c
- src/game/protos/object.c
- src/game/protos/object.h
- src/game/protos/player.c
- src/game/protos/scene.c
- src/game/protos/scene.h
- src/game/scenes/arena.c
- src/game/scenes/arena.h
- src/game/scenes/mainmenu.c
- src/game/utils/ticktimer.c
- src/game/utils/ticktimer.h
Fixed an unsafe clone of the scene ticktimer, removed some more obsolete code, removed overcomplicated 'seen_peer' event tracking and made sure when we save the game state we've applied any inputs for that frame.
> Simplify netplay and remove bugs

- src/audio/backends/sdl/sdl_backend.c
This is to avoid a linking issue in the packages if the SDL2 Mixer package is older than 2.6.0.
See https://wiki.libsdl.org/SDL2_mixer/Mix_PlayChannel for more details. The bug was reported on Ubuntu 22.04 LTS which has SDL2 Mixer 2.0.4.
> Use Mix_PlayChannelTimed instead of Mix_PlayChannel

- .github/actions/version/action.yml
- .github/workflows/compilation.yml
- CMakeLists.txt
If git describe version has a label, increment patch version
The goal here is to keep versions built from branches past the last
release tag to always have a newer version relative to the last tag.
This is done by incrementing the patch component of the version if
there's a 'label' on the version git describe returns.
> Experiment with auto versioning

- src/formats/palette.c
- src/formats/palette.h
- src/game/scenes/cutscene.c
Don't use the altpals indices, as those are not used in tournament mode, instead use the palette stored in the CHR file.
> Rewrite expanded colors to use the pilot's palette

- src/controller/net_controller.c
- src/game/scenes/arena.c
In peer to peer netplay, you return to MELEE after the fight, so make sure the wins/losses are tracked properly, like in 2 player mode.
Additionally, set the reliable flag on the propose/accept start packets, so they cannot be lost.
> Make netplay startup faster and more reliable, fix win tracking in netplay

- src/controller/net_controller.c
- src/game/scenes/lobby.c
- src/game/utils/nat.c
- src/game/utils/settings.c
- src/game/utils/settings.h
- src/main.c
* Lobby joining doesn't block the game anymore and can be cancelled
* NAT uPNP and NAT-PMP can be cancelled if they hang
* Connection errors are displayed as dialog boxes
* The address of the lobby server can be provided on the command line or in the config file
* Fix a bug in NAT-PMP detection where it would try a non-existant server multiple times
> Improvements to joining the network lobby

- src/game/objects/har.c
I confirmed the current value is slightly too high, and 32 matches the original:
> Adjust close distance to match original game

- src/game/scenes/mechlab.c
- src/game/scenes/mechlab.h
- src/game/scenes/mechlab/lab_dash_main.c
- src/game/scenes/mechlab/lab_menu_main.c
If there's no 'last' character found, and you try to load one, without this patch the HARs would not display in the character select.
Additionally, if you cancelled the har load, the game would crash going back to the main mechlab menu.
> Fix various bugs when entering tournament mode with no character

- src/game/objects/har.c
Implement the animation string search strategy for hyper/normal/enhancement animation strings when loading the HAR.
Essentially, in normal 1/2 player mode, if extra string 0 exists and is not blank or '!', use it. In hyper mode if extra string 1 exists and is not blank, use it.
For tournament mode, if the user has an enhancement, check index 1+enhancement level, if that exists, use it, otherwise use the highest populated string in the extra strings table. If there's no enhancement, honor the hyper mode setting.
> Add support for hyper mode and tournament enhancements

- src/controller/net_controller.c
- src/game/objects/har.c
- src/game/protos/object.h
- src/game/scenes/vs.c
When we were deduping inputs, we were not considering the direction the
HAR was facing. This led to a case where if you jumped over the opponent
and kept holding the forward and jump keys, once you landed the HAR, on
rollback, would start jumping the other way. This is because we were
encoding the direction into the input buffer, but not when deduping, so
because the direction of the HAR changed, we need to allow the new input
to come through.
Additionally, the dedup has been corrected so that if the last event the
player has not changed, and the HAR's direction has not changed, there
is no need to store or send any input events. This significantly reduces
the network events sent and thus the rollbacks that need to be done.
> Make rollback perfectly consistent with local play & improve dedup

- src/game/objects/har.c
- src/game/objects/har.h
- src/game/protos/player.c
- src/game/scenes/arena.c
Many of the scrap animations have the winner walk over to where the loser is lying on the ground and pick them up, or ruin them where they lay, etc.
Shadow's scrap has the winner walk to the far arena wall and lean against it.
Both of these are now implemented.
Additionally several bugs with the ez-destruct cheat were fixed, and going to non-scrap/destruction moves during scrap/destruction are now properly disallowed.
> Implement "walk to HAR" used in several scrap animations

- src/controller/ai_controller.c
When the HAR is far enough away, release the avoid state.
> Avoid AI deadlock in avoid state

- .github/actions/build_macos_arm/action.yaml
- .github/actions/build_mingw/action.yaml
- .github/actions/build_msvc/action.yaml
- .github/actions/build_ubuntu/action.yaml
- .github/workflows/compilation.yml
- CMakeLists.txt
- src/game/gui/textinput.c
- src/game/gui/textinput.h
- src/game/scenes/mainmenu/menu_connect.c
- src/game/scenes/mainmenu/menu_listen.c
- src/game/utils/nat.c
- src/game/utils/nat.h
First commit makes our upnp work on my netgear router (which gives an err 725), second commit enables the miniupnpc and natpmp libraries by default in all builds, third commit adds the ability to enter a port on the connect screen.
I don't want to add a port setting to the "Start Server" dialog, because it mostly ignores it and likes to try random ports until it finds an available one. Players are expected to communicate their IP and port from server player to client player.
> Netplay Connection fixes

- src/game/objects/har.c
- src/game/protos/player.c
- src/game/protos/player.h
- src/game/scenes/arena.c
* Count the round over as soon as a player has 0 health
* Defer the you lose/win animation until both hars are at rest
The goal here is to be more like the original, where you instantly lose input control (other than scrap/destruction) and there's not a weird gap before the round starts to end.
> Try to make fight rounds end smoother:

- src/game/objects/har.c
This can happen with katana's rising blade or wall spin, among others.
> Fix STATE_NONE while doing a crouching move that goes airborne

- src/game/objects/har.c
Without this fix, the losing HAR was not put in the correct state after death. Found via demo fuzzing in a katana vs katana fight.
> Fix rare case where both hars hit each other simultaneously and one dies

- src/game/gui/progressbar.c
- src/game/gui/progressbar.h
- src/game/scenes/arena.c
- src/game/scenes/melee.c
This makes the health/endurance meters more like the original.
> Allow progressbars to animate when they're lowering

- src/controller/ai_controller.c
- src/controller/controller.c
- src/controller/keyboard.c
- src/controller/net_controller.c
- src/controller/rec_controller.c
- src/engine.c
- src/engine.h
- src/formats/rec.c
- src/formats/rec.h
- src/formats/setup.h
- src/game/game_state.c
- src/game/game_state_type.h
- src/game/objects/har.c
- src/game/scenes/arena.c
- src/main.c
- tools/rectool/main.c
- tools/setuptool/main.c
This patch makes REC loading/saving/playback work again, it makes REC files that the original engine can load and play and it fixes several inaccuracies in OpenOMF's input system discovered when trying to make RECs behave the same in both engines.
> Restore REC support and make compatability much better

- src/game/game_state.c
- src/game/game_state.h
- src/game/game_state_type.h
- src/game/objects/har.c
- src/game/scenes/arena.c
- src/game/scenes/lobby.c
- src/game/scenes/mainmenu.c
- src/game/scenes/mainmenu/menu_connect.c
- src/game/scenes/mainmenu/menu_listen.c
- src/game/scenes/mechlab.c
This struct avoids direct access to the global settings. This is because in some cases (tournament mode, netplay, REC playback) we don't want to use the global settings blindly. For example some options are ignored in netplay mode (eg player 1/2 power), agreeing on the options for netplay should be handled differently, and REC files contain their own set of all the gameplay settings.
> Store gameplay affecting settings in a game_state struct

- src/game/objects/har.c
There are a few tests here that confirmed our input buffering was wrong:
* You could chain from Jaguar 1k into k without releasing directional keys
* Electra allowed 65K6P in the original but not in openomf
> Attempt to make input buffering the same as the original

- src/game/objects/har.c
- src/game/protos/object.c
- src/game/protos/object.h
- src/game/protos/player.c
The Q tag should allow subsequent hits if the # of hits this move has made already is less than the value of Q. For example a move like A1-q2B1-q2C1 should only hit twice, the second hit coming either on the B or C frame, but A1-q2B1-q3C1 can hit 3 times.
> Fix Q tag implementation

- src/controller/controller.c
this recently regressed with commit a80be6c4dde6efc6d7dcd027411577c85aa8aade, because the debouncing logic I wrote assumed actions would never be combined into one action bitmask (e.g. `ACT_PUNCH | ACT_RIGHT`)
> Fix controller_cmd action debouncing

- src/game/scenes/mainmenu/menu_video.c
- src/game/scenes/mainmenu/menu_video_confirm.c
- src/game/utils/settings.h
- src/utils/c_string_util.c
- src/utils/c_string_util.h
While testing https://github.com/omf2097/openomf/pull/898, the video settings' "renderer" string was some version of wild free (could have been a bug from master? wasn't able to repro with openomf_0.7.2-524-g071faf17_windows.zip release)
ASan didn't feel like giving me any more info (no alloc site, first free site, or anything), and it occured to me that the settings library would probably support fixed sized strings (which, it does!).
So, no more dynamically allocated `renderer` and associated bugs.
> Use fixed size string in video settings

- src/formats/pilot.c
- src/formats/pilot.h
- src/formats/rec.h
- src/formats/sprite.c
- src/game/scenes/arena.c
- Tournament pilots names no longer get saved as "Crystal"
- Tournament pilots colors are now saved, and are loaded correctly (without being overwritten by colors from ALTPALs.)
- Watching player 1 win a tournament match in a REC no longer crashes the game trying to rank them up.
- Tournament pilots photos are now saved and loaded to REC, visible in replays.
Also: tested working with .RECs from DOS, ~~although the tournament rec caused some unrelated pointer problems regarding the round-end tournament score calculations.~~ fixed that crash.
> Tournament REC fixes

- src/engine.c
- src/formats/pilot.c
- src/formats/pilot.h
- src/game/game_state.c
- src/game/scenes/mechlab.c
- src/game/scenes/mechlab/lab_dash_main.c
- src/game/scenes/mechlab/lab_menu_customize.c
- src/game/scenes/melee.c
- src/resources/sgmanager.c
I tested these changes by copy-pasting CHR's and RECs between OMF and openomf.
- Colors are now ordered correctly: TERTIARY, followed by SECONDARY, and finally PRIMARY.
- Tournament save-games from DOS now load fully: Previously, the HAR colors would be all-black.
- The mechlab now lets you select the PIC colors (color number 16) in the customization screen.
- A crash was fixed, where by mashing F3 and ALT-F4 the game would try to save a recording after the recording was already freed and nulled.
> Correct color order, and fix tournament colors save-compatibility

- run_rectests.sh
This permits quote marks in rectest descriptions.
> Use 'sed' instead of 'xargs' to trim whitespace in run_rectests.sh

- .github/workflows/compilation.yml
- .github/workflows/functional.yml
- lsan.supp
- run_rectests.sh
This is to speed up the CI run.
> github: Extract rec_and_menu_tests from unittest job

- shaders/palette.frag
- src/game/objects/har.c
- src/game/protos/object.c
- src/game/protos/object.h
- src/video/enums.h
Electra electricity and Pyros Fire use palette indexes from outside the HAR range (first 48 colors), and should skip remapping to ensure they remain bright and colorful.
Part of issue #649
<details><summary>Visual Comparison, on Stadium (positional lighting remap is in effect)</summary>
Before:
After:
</details>
> gl3: Implement Electra & Pyros palette quirks

- src/controller/controller.c
- src/controller/rec_controller.c
- src/formats/actions.h
This fixes a desync where rec_controllers would let go of buttons after rewinding.
> Recalculate last held inputs when rewinding rec controller

- shaders/palette.frag
- src/game/protos/object.c
- src/resources/sprite.h
- src/video/enums.h
- src/video/renderers/opengl3/helpers/object_array.c
There's a [soft-shadows](https://github.com/omf2097/openomf/tree/soft-shadows) branch which implements this by creating a copy of the surface on the CPU, but I think we'd prefer to do it in shader.
To make the OMF soft shadow effect, we make not one but four samples of the texture as a mask and add them up-- this coverage determines which of the four first remaps we use to make the shadow.
> Implement soft shadows in GLSL

- CMakeLists.txt
- src/game/gui/progressbar.c
- src/game/gui/progressbar.h
- src/game/scenes/melee.c
Players can enable the pilot stats cheat by moving their cursor across all pilots and wrapping on both rows, then pressing KICK.
While holding KICK, the stats can be reallocated with the directional input.
> Implement pilot stats cheat from the original

- src/game/scenes/melee.c
Regressed in my recent pr, #1067.
Was accidentally loading a bunch of Crystal's data instead of Shirro when creating the melee scene.
> Properly load Shirro for second player in 2-player scene

- src/game/protos/object.c
Very silly bug, controlled projectiles go the wrong way vertically depending on facing.
> Fix CY When Facing Left

- src/game/protos/player.c
Volume is already applied in the audio backend, so player.c should not be doing this.
Previously if the game volume was set to 1 (of 10), the round announcer & many other in-game sounds would be inaudibly quiet.
> Fix volume being applied twice to animation sounds

- shaders/palette.frag
after some poking around in ghidra, I found OMF's dissolve effect code.
Magic number 0x6B comes directly from that.
`tan(10*PHI*v.y)` is to offset each row, simulating how OMF's draw_sprite_row_dissolve would shift the pattern depending on where the row started.
<details>
<summary>Visual Comparison. OMF, OpenOMF (this PR), OpenOMF (master)</summary>
</details>
> Rewrite dissolve effects noise function

- src/game/game_state.c
- src/game/game_state.h
- src/game/scenes/lobby.c
- src/game/scenes/mainmenu/menu_connect.c
- src/game/scenes/mainmenu/menu_listen.c
- src/game/scenes/mainmenu/menu_main.c
In netplay, we sometimes want to use the player 1 keyboard controls for player 2 (the challengee). This change allows the game to apply the player 1 controls to the player 2 player for this situation.
> Allow _setup_keyboard to specify the user and which config to user

- src/console/console.c
- src/game/gui/text/text.c
- src/game/gui/text/text.h
- src/game/scenes/arena.c
- src/game/scenes/lobby.c
- src/game/scenes/mainmenu.c
- src/game/scenes/scoreboard.c
- src/game/utils/score.c
- src/game/utils/score.h
- src/resources/languages.c
Done:
- Remove trailing newline in language strings
- Make arena use the new text renderer (bacause arena texts broke due to the newline removal)
- Some color define fixes
> Language loader fixes

- src/game/scenes/newsroom.c
* Only play ending cutscene after beating the real tournament champion, not any unranked challengers that trigger thereafter
* Prevent beating an unranked challenger from triggering another unranked challenger
> Fix some bugs with unranked challengers:

- src/game/objects/har.c
Fixed air knockback code overriding M200 at the end of overhead throw
> Bug Fix: Enemies can recover from overhead throw

- src/controller/net_controller.c
- src/formats/rec.c
- src/game/scenes/arena.c
This should help the netplay crash. #1153
> Don't free recs when --rec is passed on cli, fix double-free in sd_rec_free

- src/game/objects/har.c
Return from the function right away after checking for button mashing to recover faster.
> Prevent any moves while stunned

- .github/actions/version/action.yml
- .github/workflows/compilation.yml
- .github/workflows/functional.yml
- .github/workflows/release.yml
- CMakeLists.txt
- cmake-scripts/version.cmake
Advantages include:
- our Actions' clones are shallow again, and version.cmake will run a `fetch --shallow-since` as needed.
- ~~releases which fork off of the main branch (e.g. 0.8.0) are now handled elegantly-- in such cases, `LATEST_RELEASE_FORKED_FROM` should be set to the commit where the release was forked.~~
- VERSION_LABEL's commit hash is no longer prefixed with a `g`.
- Errors in the version calculation do not block the build-- instead, the version calculation error is shoved in the version's label (e.g.  `0.0.0-GITNOTFOUND`)
- builds that are after a prerelease, but before the stable release no longer get their PATCH version bumped (e.g. 3 commits after 0.8.1-rc1 no longer gets labelled as 0.8.2-rc1-2-COMMITHASH)
> Calculate version in CMake, support a shallow checkout

- cmake-scripts/version.cmake
i broke it, working to fix it in this pr.
i thought i had VERSION_REQUIRED on in CI, but didn't-- hence why this failed silently.
I'm guessing that it's failing to fetch the tags?
EDIT: Yes, failing to fetch the tags.. by thinking it already had them! the third commit is the actual fix.
> Fix versioncmake

- src/game/objects/har.c
- src/game/objects/har.h
- src/game/protos/player.c
- `am` tag with the `e` tag now stays on the ground
- `bu` tag without an upward trajectory is now a teleport to the middle
- The `bm` tag now remembers where you were in the animation before walking
- Dead bodies now use the alternate gravity constant
> Fixes for Thorn's Scrap

- src/game/protos/object.h
- src/game/protos/player.c
- src/game/protos/player.h
Undo some changes from #1183
Realized that x= is an entirely different tag from x- or x+
enemy_slide_state is still totally unused and still deleted.
> Restore Interpolator Logic

- cmake-scripts/version.cmake
The version.cmake had a couple problems:
* Would not accept a tag with no label on it (eg. 0.8.1)
* Would append the shorthash to a perfect match
> Fix some problems with version.cmake

- src/game/objects/har.c
- Fix Katana wall spin and Chronos matter phasing failing if started at the wall
> AW Trigger Fix

- src/game/objects/har.c
- src/game/objects/har.h
Currently we are creating a new animation and sprite for every single frame that needs a trail effect. Netcode rollbacks can cause this to overflow the atlas. This patch changes things so that each potential sprite that needs the trail effect only creates one animation, that is cached and reused (along with the associated sprite).
> Create a cache for the 'shadow trail' animation effects

- src/game/objects/har.c
- src/game/objects/har.h
- src/game/protos/object.c
- src/game/protos/object.h
- src/game/protos/player.c
fixes #329 
- UG moves are treated as airborne (Electra rolling thunder, Shredder headbutt)
- AG allows blocking from both sides (Jaguar overhead throw, Katana wallspin)
Reworked blocking so that a player must hold the direction to continue blocking
> Implemented AG and UG tags

- src/game/objects/har.c
Thorn's scrap uses a different tag than other scrap moves, so another check needs to be done to disable it
> Fix Scrap Before Match End

- src/controller/net_controller.c
- src/game/game_state.c
- src/game/objects/har.c
- src/game/protos/object.c
- src/game/protos/object.h
- src/game/scenes/arena.c
Also, this adds the random seed to the arena hash so it's easier to detect a desync like this. Also adds some logging improvements for debugging.
> Fix fire orb random to not desync netplay
