omf2097/openomf

- src/game/gui/menu_background.c
- src/game/gui/text_render.c
- src/game/scenes/mainmenu/menu_configuration.c
- src/game/scenes/vs.c
> Look and feel

- src/game/scenes/vs.c
Redid that ugly code by some printf magic. Repeated use of strlen should be optimized out by compiler.
> Refactoring of new line stripping

- CMakeLists.txt
- INSTALL.md
- include/audio/music.h
- include/audio/source.h
- include/audio/sources/dumb_source.h
- include/audio/sources/modplug_source.h
- include/audio/sources/xmp_source.h
- include/game/scenes/mainmenu/menu_audio.h
- include/game/utils/settings.h
- src/audio/music.c
- src/audio/source.c
- src/audio/sources/dumb_source.c
- src/audio/sources/modplug_source.c
- src/audio/sources/xmp_source.c
- src/game/scenes/mainmenu/menu_audio.c
- src/game/scenes/mainmenu/menu_configuration.c
- src/game/utils/settings.c
Adds:
- New audio menu to configuration
- Module playback library selection to audio menu
- Frequency selection
- Resampler selection
- Moves mono, music volume, sound volume options to audio menu
- New settings options
- Audio library now allows setting frequency and resampler in module music sources.
> Audio menu

- src/game/game_state.c
- src/game/objects/har.c
This PR will move part of the slowdown handling to har.c. This is meant to have simpler control of time slowdown. The other commit is to make a big slowdown at last shot, like in OMF.
Related to #308 and a little to #290
> Slowdown tweaks

- src/utils/hashmap.c
- testing/test_hashmap.c
This should fix the double insert problem in an optimized manner.
@Vagabond When you have the time, please run through this your tests.
> Fix hashmap_put double insert problem + add unittest

- .travis.yml
- external/CMakeLists.txt
- travis/deps.sh
- travis/make.sh
This updates travis to use trusty for compiling everything.
> Update Travis to use Trusty

- include/game/protos/player.h
- src/controller/net_controller.c
- src/game/objects/har.c
- src/game/protos/object.c
- src/game/protos/player.c
- src/game/scenes/arena.c
This does a pretty heavy change on how certain movement tags are handled. Makes the game feel quite a bit more like the original, especially with HARs previously broken (Gargoyle, Shredder).
> Properly handle movement tags

- src/game/protos/object.c
- src/game/protos/player.c
> Jumping tests

- src/controller/controller.c
- src/controller/net_controller.c
- src/game/gui/component.c
- src/game/gui/menu.c
- src/game/gui/spritebutton.c
- src/game/gui/textbutton.c
- src/game/gui/textinput.c
- src/game/gui/textselector.c
- src/game/gui/textslider.c
- src/game/gui/xysizer.c
- src/game/scenes/mainmenu.c
- src/game/scenes/mainmenu/menu_connect.c
- src/game/scenes/mainmenu/menu_listen.c
- src/game/utils/serial.c
Poke at it with a long stick and see if it bites :/
> Feeble attempts at fixing network stuff

- src/game/scenes/arena.c
> game: Initialize move to prevent crash later when freeing rec

- src/console/console.c
- src/console/console_cmd.c
- src/game/gui/menu.c
- src/game/gui/trn_menu.c
cosmetic stuff from sonarcloud
> If statement merges

- src/formats/rec.c
Previous merging of the if statements was sloppy, but this version
should make the static analyser happy.
> formats: Remove side effects from right of && in sd_rec_load()

- .travis.yml
Xenial is quite obsolete already.
> travis: Upgrade distro to focal

- .github/workflows/compilation.yml
> Release pipeline

- include/controller/ai_controller.h
- include/game/game_player.h
- include/game/objects/har.h
- include/utils/str.h
- src/controller/ai_controller.c
- src/game/game_player.c
- src/game/game_state.c
- src/game/objects/har.c
- src/game/scenes/arena.c
- src/game/scenes/newsroom.c
- src/utils/str.c
AI is a bit more fun to play against now but still a bit too timid for my liking at the higher difficulties.
**AI Rework:**
* Scale jump, move, and attack tendency with AI difficulty
* Populate pilot personality stats in arcade mode
* Queue tactics in response to HAR events (depending on difficulty and personality)
* Favor attack types that the pilot personality likes
**HAR object changes:**
* Fire extra har events: HAR_EVENT_BLOCK (so AI knows what attack types we have blocked when initiating a counter) & HAR_EVENT_ENEMY_STUN (so AI knows when to charge stunned enemy)
* Fire extra movement event to fix turn delay when attacking an opponent who is jumping over your head
> Snaf AI rework

- doc/Doxyfile
- include/utils/str.h
- src/controller/ai_controller.c
- src/game/gui/textslider.c
- src/game/objects/har.c
- src/game/scenes/melee.c
- src/game/scenes/newsroom.c
- src/resources/af_move.c
- src/resources/animation.c
- src/resources/bk_info.c
- src/utils/str.c
- testing/test_str.c
WIP! This is currently a design plan, not actually working code. Needs more thought... possibly inplace versions of the functions too ? What would be the easiest ?
> Extend string lib

- include/formats/internal/reader.h
- include/formats/internal/writer.h
- src/formats/internal/reader.c
- src/formats/internal/writer.c
These will allow us to easily read and write str objects in parsers.
> Add string handling to file reader and writer

- .clang-format
- .clang-tidy
- CMakeLists.txt
- src/controller/ai_controller.c
- src/controller/net_controller.c
- src/game/gui/text_render.c
- src/game/objects/har.c
- src/game/objects/hazard.c
- src/game/scenes/arena.c
- src/game/utils/score.c
A cleanup of clang-tidy config + toggle performance options
> Tidy improvements

- include/audio/audio.h
- include/audio/music.h
- include/audio/sources/dumb_source.h
- include/audio/sources/xmp_source.h
- include/console/console_type.h
- src/audio/audio.c
- src/audio/music.c
- src/audio/sources/dumb_source.c
- src/audio/sources/raw_source.c
- src/audio/sources/vorbis_source.c
- src/audio/sources/xmp_source.c
- src/console/console_cmd.c
- src/game/scenes/mainmenu/menu_audio.c
> Audio cleanups

- src/formats/palette.c
- src/game/scenes/newsroom.c
Also fix a bug where losing would randomize your next opponent in tourmanent mode and fix a palette bug in the tournament ending cutscene.
> Fix bug where losing once in tournament made you lose forever

- .github/workflows/compilation.yml
> Bump gcc 11 -> 13, clang 11 -> 15

- CMakeLists.txt
> CMakeLists.txt: Copy openomf.bk to destination resources

- src/audio/audio.c
- src/game/game_state_type.h
- src/game/protos/fight_stats.h
- src/game/protos/object.c
- src/game/scenes/arena.c
- src/game/scenes/mainmenu.c
- src/game/scenes/mechlab.c
- src/game/scenes/mechlab/lab_dash_main.c
- src/game/scenes/vs.c
- src/game/utils/formatting.c
- src/game/utils/formatting.h
> Continue financial report

- src/game/scenes/arena.c
> Bonus score

- src/game/scenes/arena.c
> game: Charge repair costs based on the har value

- .github/workflows/compilation.yml
> github: Bump build-deb-action to v3 to fix file ownership issues

- src/game/protos/fight_stats.h
- src/game/scenes/arena.c
- src/game/scenes/mechlab/lab_menu_customize.c
- src/game/scenes/mechlab/lab_menu_customize.h
- src/game/scenes/vs.c
> game: Sell upgrades when running out of money

- src/game/gui/trn_menu.c
- src/game/gui/trn_menu.h
- src/game/scenes/mechlab.c
- src/game/scenes/mechlab/lab_menu_confirm.c
- src/game/scenes/mechlab/lab_menu_customize.c
- src/game/scenes/mechlab/lab_menu_difficultyselect.c
- src/game/scenes/mechlab/lab_menu_main.c
- src/game/scenes/mechlab/lab_menu_select.c
- src/game/scenes/mechlab/lab_menu_select.h
- src/game/scenes/mechlab/lab_menu_trade.c
- src/game/scenes/mechlab/lab_menu_training.c
Start of #533, but missing trigger on focus.
> game: Move hand back to select button on select menus

- src/controller/net_controller.c
This handles the case when we get delayed packets out of order.
> Make last received and last acked ticks only go up

- shaders/palette.frag
- shaders/rgba.frag
> More GL fixes, part 1

- shaders/rgba.frag
- src/game/protos/object.c
- src/game/protos/player.c
- src/video/enums.h
- src/video/opengl/object_array.c
- src/video/opengl/object_array.h
- src/video/opengl/remaps.c
- src/video/opengl/remaps.h
- src/video/video.c
- src/video/video.h
Cleaned up things from https://github.com/omf2097/openomf/pull/620
> OpenGL improvements, part 3

- src/engine.c
This seems to no longer be required.
> Drop unneeded tick hack-fix

- src/game/objects/har.c
- src/game/objects/projectile.c
- src/game/objects/projectile.h
- src/game/protos/player.c
Remaining issue for shadow grab is releasing the HAR when the shadow fades and fading the shadow if the grabbed har is hit.
The shadow fading when the har is hit is managed with the 'uz' tag. The 'ua' tag in the grab animation keeps the HAR looping in the struggle animation.
> Get shadow grab to mostly work

- src/game/scenes/melee.c
- src/utils/str.c
- src/utils/str.h
* only do string formatting when needed
* only create 1 object per HAR, just switch animations
> Improve the melee scene:

- src/game/gui/component.c
- src/game/gui/spritebutton.c
- src/game/gui/trn_menu.c
- src/game/gui/widget.c
- src/game/protos/object.c
> game: Do not print a debug message when sprite 25 is not found

- src/formats/tournament.c
- src/resources/pathmanager.c
- src/resources/pathmanager.h
- src/resources/trnmanager.c
- src/utils/scandir.c
Windows findfile api expects a wildcard.
Windows path seperator is not forward slash.
> Fix tournament on Windows

- src/game/gui/progressbar.c
- src/game/gui/text_render.c
- src/game/gui/text_render.h
- src/game/scenes/mechlab/lab_dash_main.c
- src/game/scenes/melee.c
- src/game/scenes/newsroom.c
- src/game/scenes/vs.c
- testing/test_text_render.c
Newsroom now breaks text more faithfully.
Centered the pilot bio in pilot select
> Text quirks

- src/game/game_state.c
- src/video/vga_state.c
- src/video/video.c
- src/video/video.h
Done:
- Crossfade
- Screen shakes
> More renderer fixes

- .github/workflows/compilation.yml
- CMakeLists.txt
- src/game/utils/serial.c
- tools/bktool/main.c
- vcpkg.json
small extra change: renamed bktool's function bk_info bk_getinfo because `bk_info` is already the name of the struct bk_info_t typedef
> Precompiled Headers & Faster CI

- src/game/objects/har.c
- src/game/protos/object.c
- src/video/vga_state.c
- src/video/vga_state.h
Also fixed off-by-one error in the assert.
> Fix vga_state memory bugs

- tools/languagetool/main.c
This showed up in DEBUG mode on mingw-w64
> Compilation problem

- src/console/console.c
- src/console/console_type.h
- src/game/gui/menu.c
- src/game/gui/menu.h
- src/game/gui/menu_background.c
- src/game/gui/menu_background.h
- src/video/video.c
- src/video/video.h
Mainmenu + console transparency.
Are there others ?
> Menu transparency

- src/game/gui/label.c
- src/game/gui/text_render.c
- src/game/gui/text_render.h
- src/game/scenes/lobby.c
- src/utils/str.c
- testing/test_text_render.c
> Various UI and lobby fixes

- shaders/palette.frag
- shaders/palette.vert
- src/game/protos/object.c
- src/game/protos/scene.c
- src/video/opengl/object_array.c
- src/video/opengl/object_array.h
- src/video/video.c
- src/video/video.h
Decimate pixels to make the object disappear. This implements the bs/bf tags.
Note that the decimation function can still be improved (if wanted).
> Implement pixel decimation

- src/engine.c
- src/video/damage_tracker.c
- src/video/opengl/object_array.c
- src/video/vga_state.c
- src/video/vga_state.h
So I quickly tried the new code, and it broke Credits. Removing these seems to fix things. After looking at these, I don't quite understand what they are meant to do that the original code doesn't already do ?
> Remove extraneous

- src/engine.c
- src/formats/script.c
- src/formats/script.h
- src/game/protos/object.c
- src/game/protos/object.h
- src/game/protos/player.c
- src/game/protos/player.h
- testing/test_script.c
Nothing really earth-shaking, I think. The sd_script changes are for making writing debugging code easier (and possibly tooling at later date).
> Miscellaneous render fixes

- src/game/scenes/mainmenu/menu_video.c
Quick fix to the default renderer selection
> Select correct renderer in video settings

- src/audio/audio.c
- src/console/console.c
- src/console/console.h
- src/console/console_type.h
- src/engine.c
- src/resources/fonts.c
- src/resources/fonts.h
- src/resources/languages.c
- src/resources/languages.h
- src/resources/sounds_loader.c
- src/resources/sounds_loader.h
> Use boolean in more places

- src/game/scenes/cutscene.c
Fixes https://github.com/omf2097/openomf/issues/779
> Fix #779: Missing lightning in katushai cutscene

- CMakeLists.txt
This shows up as the window title
> Bump version in CMakeLists.txt to 0.7.0

- src/controller/net_controller.c
- src/engine.c
- src/game/game_state.c
- src/game/gui/textbutton.c
- src/game/gui/textbutton.h
- src/game/objects/har.c
- src/game/objects/har.h
- src/game/protos/player.c
- src/game/scenes/arena.c
- src/game/scenes/mainmenu/menu_connect.c
This is some junk I had kicking around in a branch, but it does seem to dramatically help with netplay latency. Needs more testing though.
> Netplay: improve latency

- src/game/gui/text_render.c
- src/game/gui/text_render.h
- src/game/gui/textinput.c
- src/game/scenes/lobby.c
* Fix textinput cursor to support variable width font
* Adjust some padding errors
* Fix a crash when using Refresh
> Make some lobby improvements:

- .github/workflows/compilation.yml
- CMakeLists.txt
- resources/flatpak/org.openomf.OpenOMF.metainfo.xml
Fixes include:
* Flatpak support
* Fix HAR colors in tournament cutscenes
> Prepare for 0.7.1

- src/controller/net_controller.c
- src/game/scenes/arena.c
- src/game/scenes/arena.h
Added fields:
* Arena ID
* Pilot endurance
* Pilot power
* Pilot agility
* HAR ID
* Har's current animation ID
> Add more fields to the arena state hash in netplay

- .github/actions/assets/action.yaml
- .github/actions/build_macos_arm/action.yaml
- .github/actions/build_mingw/action.yaml
- .github/actions/build_msvc/action.yaml
- .github/actions/build_ubuntu/action.yaml
- .github/workflows/compilation.yml
- .github/workflows/release.yml
Cleanups + add a manual release action
> CI: Cleanups and Release action

- src/controller/controller.c
- src/controller/controller.h
- src/controller/net_controller.c
- src/engine.c
- src/game/game_state_type.h
- src/game/objects/har.c
- src/game/objects/har.h
- src/game/scenes/arena.c
- src/game/scenes/lobby.c
- src/game/utils/nat.c
- src/game/utils/settings.c
- src/game/utils/settings.h
- src/main.c
* Slow one side down if it's consistently rendering frames faster than expected
* Dedup inputs to avoid needing to send so often and allow us to rely more on prediction
* Rework HAR input to operate entirely from the input buffer
> Improve performance and correctness of netplay

- src/controller/ai_controller.c
* Avoid some projectiles if the har is too close/too far
* Return true only if the function actually chose a move
> Improve some AI strategies

- src/game/objects/har.c
* Fixes #814 When walking away from a HAR, restore normal walking speed
* Pushback from a move decreases over time if you're touching the ground. This is commonly seen when you do like a roundhouse while the enemy is up against the wall, you'll be pushed back for the duration of the attack animation.
> Fix 2 movement bugs:

- src/formats/palette.c
This bug was introduced by commit a1e6df845daaca348ae7e4e70986eeb52f847e29.
Fixes #891
> Fix corruption in palette_set_player_expanded_color

- src/controller/net_controller.c
- src/game/scenes/lobby.c
- src/game/scenes/mainmenu/menu_connect.c
- src/game/scenes/mainmenu/menu_listen.c
* Change a bitfield to a simple enum
* Support server announcements
* Support other kinds of challenge error
* Fix some cancel behaviours
> Break the lobby protocol a bit:

- src/game/scenes/arena.c
This fixes arena end hook crashing in one player mode.
> game: Only fill fight stats after arena for tournament mode

- src/controller/ai_controller.c
* Release jump key after jumping
* Will eventually generate a tactic if it doesn't know what to do
> Fix some cases where the AI would get stuck

- src/controller/ai_controller.c
- src/controller/ai_controller.h
- src/game/scenes/arena.c
> In debug builds, show the AI internal state onscreen

- src/game/scenes/lobby.c
> Make the lobby messages longer for MOTD and quips

- src/game/scenes/mainmenu/menu_listen.c
- src/game/utils/nat.c
- src/game/utils/nat.h
* Obtain and display external IP/port on the network listen screen
* Handle additional upnp errors
* Retrieve WAN address via PMP
> Various improvements to PR#901

- src/game/objects/har.c
Part of this patch was accidentally added in #919
> Ensure HAR always has a state, finishes work from #919

- src/utils/vector.c
- src/utils/vector.h
- testing/test_vector.c
- Add free() callback for item removal
- Drop vector_prepend() as useless -- if you need it, then you probably want list or ringbuffer instead.
> Vector improvements

- src/game/objects/har.c
- src/game/objects/har.h
Fixes #932 
Shows hit pixels and a HAR origin axis when f6 is pressed:
> Fix the visual debugger

- src/game/scenes/arena.c
Just a quick change as my first PR, replaced some old handling with cleaner code and copied the animation string exactly from MASTER.DAT
> Improve Wall Splat

- src/formats/rec.c
- tools/rectool/main.c
* Correctly write non input 'extra data'
* Don't crash on missing extra data
* Better error messages
> Fix some issues with editing/saving REC files

- src/game/objects/har.c
If p1 threw p2, ignore what p2 is doing. If p2 threw p1, AND p1 didn't also do a throw, ignore p1's attack.
> Make throws have priority

- src/game/objects/scrap.c
This makes REIN feel more natural.
> When scrap hits the floor, add some sideways random jitter.

- src/game/game_state.c
- src/game/game_state.h
- src/game/game_state_type.h
- src/game/objects/har.c
- src/game/utils/settings.c
Restore code lost from #934 somehow
> Restore lost hit-pause PR

- src/game/gui/gui_frame.c
- src/game/gui/gui_frame.h
- src/game/gui/menu.c
Self-contained fix, spun out from the theme/text-renderer side.
> gui: Hide gui_frame struct to C file

- src/game/game_state.c
- src/game/scenes/arena.c
- src/game/scenes/melee.c
- src/game/scenes/vs.c
* Use the pilot struct directly from the REC
* Always use the pilot name field; ensure it it set in 1/2 player
> Fix a few issues with REC playback:

- src/game/objects/har.c
- src/game/scenes/arena.c
Falling now behaves much more like the original game
Removed a bunch of places where horizontal velocity is cancelled that are no longer needed
Moving towards the wall no longer immediately cancels your velocity
> Better Falling Behavior + Misc Nits

- src/game/game_state.c
- src/game/objects/har.c
- src/game/objects/projectile.c
- src/game/protos/player.c
Only try to keep HARs onscreen, let projectiles fly free
> Fix projectiles hitting wall

- src/game/objects/har.c
- src/game/objects/har.h
- src/game/protos/player.c
- Throw damage timing
- Throw velocities and positioning
- *bonus* removed the check that disallows hitting after KO (try a multi-hit move and you'll see)
BUG: KO doesn't happen if you try to finish a round with a throw, not sure why
> Adjust Throw Behavior

- cmake-scripts/ClangFormat.cmake
Clang-format improvements (the .clang-format changes seem to be needed for clang-format 20)
> Clang format improvements

- src/controller/joystick.c
This is required after the input improvements we made.
> Update joystick controller to combine inputs

- src/controller/net_controller.c
- src/game/game_state.c
- src/game/scenes/arena.c
Fix health/stamina bars jumping back up during replay. Fix hit-pause not inrementing game ticks.
Also remove some logspam
> Fix 2 issues with netplay

- src/game/protos/player.c
- src/game/scenes/arena.c
Also, properly mark hazards as hazards, not projectiles.
> Try to fix lighting sounds (in powerplant now) another way

- src/game/utils/settings.c
I thought it supported this already and didn't properly check. without this, a pointer is written into the char[16] renderer array, which isn't good.
This also adds an assert that each settings field is the size we expect for its type.
> Add fixed string support to settings

- src/formats/rec.c
- src/formats/rec.h
- src/game/game_state.c
- src/game/game_state_type.h
- src/game/objects/har.c
- src/game/protos/object.c
- src/game/scenes/arena.c
- src/game/scenes/mainmenu.c
- src/game/scenes/mainmenu/menu_gameplay.c
- src/game/scenes/vs.c
- src/game/utils/score.c
- src/game/utils/score.h
- tools/rectool/main.c
Various fixes for things that happen in-game.
> Misc. Gameplay Fixes

- src/audio/backends/sdl/sdl_backend.c
- src/audio/sources/psm_source.c
- src/utils/png_reader.c
- src/utils/png_writer.c
> Static version checks

- src/console/console_cmd.c
- src/controller/controller.c
- src/controller/controller.h
- src/controller/rec_controller.c
- src/engine.c
- src/formats/rec_assertion.c
- src/formats/rec_assertion.h
- src/game/game_state.c
- src/game/game_state.h
- src/game/scenes/arena.c
- src/game/utils/har_screencap.c
- tools/rectool/main.c
The REC controller will take a game state snapshot every 10 ticks, and using backspace when replaying a REC will step the game state back to the last snapshot.
> Implement time travel for the visual debugger

- src/game/gui/component.c
- src/game/gui/component.h
- src/game/gui/filler.c
- src/game/gui/label.c
- src/game/gui/menu.c
- src/game/gui/menu.h
- src/game/scenes/lobby.c
- src/game/scenes/mainmenu/menu_listen.c
- src/game/scenes/mechlab/lab_dash_main.c
Move help text rendering on top of the new text renderer.
> More text renderer changes

- src/formats/animation.c
- src/formats/bkanim.c
- src/formats/chr.c
- src/formats/language.c
- src/formats/move.c
- src/formats/tournament.c
- src/game/game_state.c
- src/game/scenes/newsroom.c
This will find places where assets break size limits.
> global: Use strncpy_or_abort over strncpy_or_truncate on assets

- src/game/game_state.c
- src/game/game_state.h
- src/game/scenes/arena.c
When playing back a REC, do not feed REC inputs into a REC again
> Fix issue when annotating RECs from console

- src/game/game_state.c
- src/game/scenes/melee.c
- src/game/scenes/newsroom.c
- src/resources/pilots.c
- src/resources/pilots.h
Most of these were missed in PR https://github.com/omf2097/openomf/pull/1027
> Fix pilot colors array being backwards sometimes

- src/engine.c
- src/game/scenes/mainmenu/menu_video.c
- src/game/scenes/mainmenu/menu_video_confirm.c
- src/game/utils/settings.c
- src/game/utils/settings.h
- src/video/renderers/null/null_renderer.c
- src/video/renderers/opengl3/gl3_renderer.c
- src/video/renderers/renderer.h
- src/video/video.c
- src/video/video.h
> gl3: Framerate limiter.

- src/console/console_cmd.c
- src/game/gui/button.c
- src/game/gui/component.c
- src/game/gui/label.c
- src/game/gui/spritebutton.c
- src/game/gui/text/text.c
- src/game/gui/text/text.h
- src/game/gui/textinput.c
- src/game/gui/textselector.c
- src/game/gui/textslider.c
- src/game/scenes/melee.c
- src/game/scenes/scoreboard.c
Use the new text renderer in scoreboard + more correctness fixes.
> Scoreboard fixes

- src/console/console_cmd.c
- src/controller/rec_controller.c
- src/engine.c
- src/game/scenes/arena.c
- src/utils/log.c
gs->int_tick is a nice monotonically increasing tick counter for netplay.
It is not a counter of dynamic ticks.
Use gs->tick instead
> Only use int_tick inside of net_controller

- src/console/console.c
- src/console/console_type.h
- src/game/gui/text/text.c
- src/game/gui/text/text.h
Use new text renderer in console. Also other fixes.
> Console text fixes

- src/console/console.c
> console: clean up more remnants

- src/game/gui/textselector.c
- src/game/scenes/mainmenu/menu_advanced.c
- src/game/scenes/mainmenu/menu_advanced.h
- src/game/scenes/mainmenu/menu_gameplay.c
> Implement advanced menu and disable the options we don't support yet

- src/game/objects/har.c
Projectile must be owned by the HAR and have the corresponding animation ID. The md tag is only used in the shadow grab in a HAR context.
> Implement 'md' tag for HARs to delete an existing projectile

- .github/workflows/release.yml
> Remove unnecessary tag creation step

- src/game/scenes/mainmenu/menu_keyboard.c
> Don't set button text before button_init has been called

- src/controller/net_controller.c
- src/controller/rec_controller.c
- src/game/scenes/arena.c
* Don't write a final event in the wrong tick timebase
* Don't ignore REC events if there's a final tick with the wrong timebase
> Fix some issues with netplay RECs:

- src/game/scenes/arena.c
- Use the new text renderer to handle debug layer
- Move debug text ticks to dyntick function
> Move arena debug layer to use the new text renderer

- src/console/console_cmd.c
- src/formats/chr.c
- src/formats/chr.h
- src/game/common_defines.c
- src/game/common_defines.h
- src/game/gui/component.c
- src/game/gui/spritebutton.c
- src/game/gui/trn_menu.c
- src/game/gui/trnselect.c
- src/game/protos/scene.c
- src/game/scenes/cutscene.c
- src/game/scenes/mainmenu/menu_help.c
- src/game/scenes/mechlab.c
- src/game/scenes/mechlab.h
- src/game/scenes/mechlab/lab_menu_customize.c
- src/game/scenes/mechlab/lab_menu_main.c
- src/game/scenes/newsroom.c
- src/resources/bk_loader.c
- src/resources/bk_loader.h
- src/resources/ids.c
- src/resources/ids.h
- src/resources/trnmanager.c
- src/resources/trnmanager.h
> Various Mechlab/Tournament UI Fixes

- src/formats/tournament.c
- src/formats/tournament.h
This allows some of the old fan made tournaments to load.
> Tournament enemy count is a uword not a udword

- src/console/console.c
- src/game/gui/button.c
- src/game/gui/spritebutton.c
- src/game/gui/text/text.c
- src/game/gui/textinput.c
- src/game/gui/textselector.c
- src/game/gui/textslider.c
- src/game/scenes/cutscene.c
- src/utils/str.c
- src/utils/str.h
- testing/test_str.c
I /think/ I got the str_split right. Probably. Maybe.
> Cutscene font renderer + some fixes

- src/game/scenes/newsroom.c
Use the new text renderer in newsroom.
> Use the new text renderer in newsroom

- src/game/gui/text/text.c
- src/game/scenes/vs.c
> Use new text renderer for the VS scene

- src/controller/net_controller.c
- src/game/scenes/lobby.c
- src/game/utils/nat.c
Also try to avoid a potential infinite loop
> Try to make it easier to debug NAT issues

- src/main.c
- src/utils/log.c
- src/utils/log.h
- src/video/renderers/opengl3/helpers/texture_atlas.c
> Allow setting logging level via commandline argument --log-level

- src/game/objects/har.c
- src/game/scenes/mainmenu/menu_advanced.c
- src/game/scenes/mainmenu/menu_gameplay.c
- Stun Res should work now
- Fixed some incorrect type in the advanced menu
- Enabled Vitality and Jump Height modifiers
> Implemented Stun Res and missing tournament mode stats

- src/game/scenes/melee.c
> Use the new text renderer in melee scene

- src/game/gui/text/text.c
- src/game/scenes/lobby.c
Builds on top of https://github.com/omf2097/openomf/pull/1158
This time the lobby.
> Use the new text renderer in lobby scene

- src/game/scenes/mechlab/lab_menu_customize.c
> Add newlines between HARs to trade

- src/game/objects/har.c
- src/game/protos/player.c
Grabbing shadow will now dissapate when the grabbed HAR is hit. However, the HAR is still stuck in struggling if the grab animation times out.
> Partially fix shadow grab

- src/game/objects/har.c
Accidentally merged a duplicate variable definition
> Fix Master

- src/game/objects/har.c
> Fix UR and UL mixup

- src/game/objects/har.c
> Fix Stunning After Throws

- src/game/game_state.c
- src/game/objects/har.c
- src/game/objects/projectile.c
- src/game/protos/object.h
- src/game/protos/player.c
- Hit pixels now disable for HARs when the N tag is present
- Show hit pixels for projectiles in debug mode
> Implement N tag

- src/game/objects/har.c
- src/game/objects/projectile.c
- src/game/protos/object.c
- src/game/protos/object.h
- Fix shredder hands not doing multiple hits
- Fix shadow punch freezing the opponent before it hits
- Fix electra's projectile not being controllable
> Projectile behavior fixes

- src/game/objects/har.c
- src/game/protos/object.c
- src/game/protos/player.c
- CY no longer applies to non-projectiles (Bug in the game, womp womp)
- H tag now zeroes out CX velocity (fix Flail zooming across the stage)
> Fixed CX and CY weirdness

- src/game/game_state.c
- src/game/game_state.h
- src/game/objects/har.c
- src/game/objects/har.h
- src/game/objects/projectile.c
- src/game/objects/projectile.h
- src/game/protos/object.h
- src/game/protos/player.c
> Implement UD/UZ tag properly

- src/video/surface.c
> Fix scrapes bounds check to not crash

- src/controller/controller.h
- src/controller/net_controller.c
- src/controller/spec_controller.c
- src/controller/spec_controller.h
- src/game/game_state.c
- src/game/game_state.h
- src/game/scenes/arena.c
- src/game/scenes/lobby.c
- src/game/scenes/vs.c
> Spectator mode

- src/game/scenes/newsroom.c
#1249 - Fixup to Christian challenge in North Am.
> Fix unranked challenger score bitset fields not to default to true

- src/game/scenes/arena.c
No longer sounds like an explosion
> Fix wall hit sound

- src/game/objects/har.c
- src/game/protos/object.h
- src/game/protos/player.c
- Currently doesn't do anything because hitpause isn't working
> Hitpause is now queued for the next time cp is asserted

- src/game/objects/har.c
- Enhancements now work in all game modes
- Enhancements won't override hyper/normal mode selection
> Fix Enhancement String Selector

- src/formats/rgba_image.c
- src/game/gui/textinput.c
- tools/fonttool/main.c
We cannot draw '@' in this game.
> gui: Do not let player enter '@' via textinput

- .github/actions/build_msvc/action.yaml
- .github/workflows/compilation.yml
- vcpkg.json
Stab at msvc so that we can run our unit-test also on windows-platform. This is so that we can test windows AND linux code-paths.
> Add windows unit-tests

- src/resources/resource_paths.c
- src/utils/path.c
Minor cleanups and windows bug fix
> More path fixes and improvements

- src/controller/rec_controller.c
- src/formats/error.c
- src/game/game_state.c
- src/utils/allocator.c
- src/utils/allocator_default.h
- src/utils/c_string_util.c
- src/utils/crash.c
- src/utils/crash.h
- src/utils/str.c
This might be nicer to use instead of abort() in some cases.
> Prefer crash() instead of abort()
